# Generated by Django 4.2.2 on 2023-07-17 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keymoments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='key_moments',
            name='moment_type',
            field=models.CharField(choices=[('SOCIAL', (('birth', 'Birth'), ('death', 'End'), ('love', 'Love'), ('moving', 'Moving'))), ('ACADEMIC', (('school', 'School'), ('college', 'College'), ('institute', 'Institutes'), ('self', 'Self Learned'))), ('WORK', (('hired', 'Hired'), ('fired', 'Fired'), ('own', 'Own Bussiness'), ('self', 'Independent'))), ('UNKNOWN', 'Unknown')], default='UNKNOWN', max_length=30),
        ),
    ]
